name: Push Image

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout secret-manger
        uses: actions/checkout@v2
        with:
          path: secret-manager
      - name: Build and push Docker images to quay
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          repository: xxxxxxxx/secret-manager
          registry: quay.io
          tag_with_ref: true
